MelodyCircle/Models/Step.cs
using System.ComponentModel.DataAnnotations;

namespace MelodyCircle.Models
{
    public class Step
    {
        /* Rodrigo Nogueira */
        public Guid Id { get; set; }
        public Guid TutorialId { get; set; }
        public Tutorial Tutorial { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }
        public int Order { get; set; }

        public DateTime CreationDate { get; set; }
    }
}

MelodyCircle/Controllers/StepController.cs
using MelodyCircle.Data;
using MelodyCircle.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MelodyCircle.Controllers
{
    public class StepController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private int maxSteps = 100;

        /* Guilherme Bernardino, Rodrigo Nogueira */
        public StepController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        public async Task<IActionResult> Index(Guid? tutorialId)
        {
            if (tutorialId == null)
                return NotFound();

            var steps = await _context.Steps
                .Include(s => s.Tutorial)
                .Where(s => s.TutorialId == tutorialId)
                .OrderBy(s => s.Order)
                .ToListAsync();

            var creator = await _context.Tutorials
                .Where(t => t.Id == tutorialId)
                .Select(t => t.Creator)
                .FirstOrDefaultAsync();

            var title = await _context.Tutorials
                .Where(t => t.Id == tutorialId)
                .Select(t => t.Title)
                .FirstOrDefaultAsync();

            ViewBag.TutorialId = tutorialId;
            ViewBag.Creator = creator;
            ViewBag.Title = title;

            return View(steps);
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        // GET: Step/Create
        public IActionResult Create(Guid? tutorialId)
        {
            ViewBag.TutorialId = tutorialId;

            if (tutorialId == null)
                return NotFound();

            return View();
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        // POST: Step/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TutorialId,Title,Content")] Step step)
        {
            bool hasValidationError = false;

            if (string.IsNullOrEmpty(step.Title))
            { 
                ModelState.AddModelError(nameof(step.Title), "O título é obrigatório");
                hasValidationError = true;
            }

            if (string.IsNullOrEmpty(step.Content))
            {
                ModelState.AddModelError(nameof(step.Content), "O conteúdo é obrigatório");
                hasValidationError = true;
            }

            var currentStepCount = await _context.Steps.CountAsync(s => s.TutorialId == step.TutorialId);

            if (currentStepCount >= maxSteps)
            {
                ModelState.AddModelError(string.Empty, "Limite máximo de Passos atingido para este tutorial");
                hasValidationError = true;
            }

            if(hasValidationError)
                return View(step);

            var occupiedOrders = await _context.Steps
                .Where(s => s.TutorialId == step.TutorialId)
                .OrderBy(s => s.Order)
                .Select(s => s.Order)
                .ToListAsync();

            int nextAvailableOrder = 0;

            while (occupiedOrders.Contains(nextAvailableOrder))
                nextAvailableOrder++;

            step.Order = nextAvailableOrder;
            step.CreationDate = DateTime.Now;

            _context.Add(step);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { tutorialId = step.TutorialId });
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        // GET: Step/Delete/tutorialId
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var step = await _context.Steps.FirstOrDefaultAsync(m => m.Id == id);

            if (step == null)
                return NotFound();

            return View(step);
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        // POST: Step/DeleteConfirmed
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid stepId)
        {
            var step = await _context.Steps.FindAsync(stepId);

            if (step == null)
                return NotFound();

            _context.Steps.Remove(step);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { tutorialId = step.TutorialId });
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        // GET: Step/Edit/tutorialId
        public async Task<IActionResult> Edit(Guid? id)
        {
            ViewBag.id = id;

            if (id == null)
                return NotFound();

            var step = await _context.Steps.FirstOrDefaultAsync(m => m.Id == id);

            if (step == null)
                return NotFound();

            return View(step);
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid tutorialId, [Bind("Id,TutorialId,Title,Content,Order")] Step step)
        {
            var existingStep = await _context.Steps.FindAsync(step.Id);

            if (existingStep == null)
                return NotFound($"Step with ID {step.Id} not found.");

            if (tutorialId != step.TutorialId)
                return NotFound($"The TutorialId of the step does not match the provided tutorialId");

            bool hasValidationError = false;

            if (string.IsNullOrEmpty(step.Title))
            {
                ModelState.AddModelError(nameof(step.Title), "O título é obrigatório");
                hasValidationError = true;
            }

            if (string.IsNullOrEmpty(step.Content))
            {
                ModelState.AddModelError(nameof(step.Content), "O conteúdo é obrigatório");
                hasValidationError = true;
            }

            if (hasValidationError)
                return View(step);

            else
            {
                _context.Entry(existingStep).State = EntityState.Detached;
                _context.Update(step);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index", new { tutorialId = step.TutorialId });
            }
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> CompleteStep(Guid tutorialId, Guid stepId)
        {
            var userId = _userManager.GetUserId(User);


            var subscription = await _context.SubscribeTutorials
                .Where(s => s.User.Id.ToString() == userId)
                .Include(st => st.CompletedSteps)
                .FirstOrDefaultAsync(st => st.User.Id.ToString() == userId && st.TutorialId == tutorialId);

            if (subscription == null)
                return NotFound();

            var step = await _context.Steps.FindAsync(stepId);

            if (step == null)
                return NotFound();

            bool alreadyCompleted = subscription.CompletedSteps.Any(s => s.Id == stepId);

            if (!alreadyCompleted)
                subscription.CompletedSteps.Add(step);

            else
                subscription.CompletedSteps.RemoveAll(s => s.Id == stepId);

            int savedChanges =  await _context.SaveChangesAsync();

            var subscriptionAfterSave = await _context.SubscribeTutorials
                .Where(s => s.User.Id.ToString() == userId)
                .Include(st => st.CompletedSteps)
                .FirstOrDefaultAsync(st => st.User.Id.ToString() == userId && st.TutorialId == tutorialId);

            int completedStepsCount = subscriptionAfterSave.CompletedSteps.Count;
            int totalStepsCount = await _context.Steps.Where(s => s.TutorialId == tutorialId).CountAsync();

            ViewBag.CompletedStepsCount = completedStepsCount;
            ViewBag.TotalStepsCount = totalStepsCount;

            return RedirectToAction("Index", new { tutorialId = step.TutorialId });
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        [HttpPost]
        public async Task<IActionResult> UpdateOrder([FromBody] List<Guid> stepOrder)
        {
            try
            {
                if (stepOrder == null || stepOrder.Count == 0)
                    return Json(new { success = false, message = "Invalid order list" });

                int order = 0;

                foreach (var stepId in stepOrder)
                {
                    var step = await _context.Steps.FindAsync(stepId);

                    if (step != null)
                    {
                        step.Order = order++;
                        _context.Steps.Update(step);
                    }
                }

                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Order updated successfully" });
            }

            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Error updating order: {ex.Message}" });
            }
        }

        /* Guilherme Bernardino, Rodrigo Nogueira */
        private bool StepExists(Guid tutorialId)
        {
            return _context.Steps.Any(e => e.Id == tutorialId);
        }
    }
}

MelodyCircle/Views/Step/Create.cshtml
@using MelodyCircle.ExtensionMethods
@model MelodyCircle.Models.Step

@{
    ViewData["Title"] = @Html.Translate("LB_ADDSTEP");
}

@* Eduardo Andrade, Rodrigo Nogueira, Guilherme Bernardino *@
@section head {
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css" rel="stylesheet" />
}

@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.js"></script>
    <script>
        const quill = new Quill('#editor', {
            placeholder: 'Compose an epic...',
            theme: 'snow',
        });
        let contentInput = document.getElementById("contentInput");
        contentInput.value = JSON.stringify(quill.getContents());
        quill.on('text-change', function(delta, oldDelta, source) {
            contentInput.value = JSON.stringify(quill.getContents());
        })  
    </script>
}

<div class="row justify-content-center">
    <div class="col-sm-6 bg-white rounded-3 border border-purple">
        <div class="text-end pt-3">
            <button type="button" class="btn btn-sm bg-darkPurple text-white rounded-circle " data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true"
                    title="<p>@Html.Translate("TT_ADDSTEP")</p>">
                ?
            </button>
        </div>
        <form asp-action="Create">
            <div class="form-group text-center mt-3">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-center" style="display: none;">
                <label asp-for="TutorialId" class="control-label"></label>
                <input asp-for="TutorialId" class="form-control" readonly />
            </div>
            <input type="hidden" asp-for="TutorialId" value="@ViewBag.TutorialId" />
            <div class="form-group text-center">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <label asp-for="Content" class="control-label"></label>
                <input type="hidden" asp-for="Content" id="contentInput" value="" />
                @* <textarea style="visibility: hidden;" asp-for="Content" class="" rows="4"></textarea> *@
                <div id="editor">
                    <p>Hello, <strong>World</strong></p>
                </div>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group text-center py-3">
                <input type="submit" value="@Html.Translate("LB_SAVE")" class="btn bg-purple text-white" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Step" asp-route-tutorialId="@ViewBag.TutorialId">@Html.Translate("LB_GOBACKTOSTEPLIST")</a>
</div>

MelodyCircle/Views/Step/Delete.cshtml
@using MelodyCircle.ExtensionMethods
@model MelodyCircle.Models.Step

@* Eduardo Andrade, Guilherme Bernardino *@

@{
    ViewData["Title"] = @Html.Translate("LB_DELETESTEP");
}
<div class="row justify-content-center">
    <div class="col-7 bg-white text-center rounded-3 border border-purple">

    <form asp-action="DeleteConfirmed" asp-route-stepid="@Model.Id">
        <h4 class="mt-3">@Html.Translate("LB_CONFIRMSTEPDELETE")</h4>
        <div class="mb-3">
            <input type="submit" value="@Html.Translate("LB_YES")" class="btn btn-danger px-4 mx-2" />
            <a asp-action="Index" asp-controller="Step" asp-route-tutorialId="@Model.TutorialId" class="btn px-4 btn-primary mx-2">@Html.Translate("LB_NO")</a>
        </div>
    </form>
    </div>
</div>

MelodyCircle/Views/Step/Edit.cshtml
@using MelodyCircle.ExtensionMethods
@model MelodyCircle.Models.Step

@* Eduardo Andrade, Guilherme Bernardino *@

@{
    ViewData["Title"] = @Html.Translate("LB_EDITSTEP");
}
@section head {
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css" rel="stylesheet" />
}
@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.js"></script>
    <script>
        const quill = new Quill('#editor', {
            placeholder: 'Compose an epic...',
            theme: 'snow',
        });
        let contentInput = document.getElementById("contentInput");

        let stepData = @Html.Raw(@Model.Content);
        quill.setContents(stepData);
        
        contentInput.value = JSON.stringify(quill.getContents());

        quill.on('text-change', function (delta, oldDelta, source) {
            contentInput.value = JSON.stringify(quill.getContents());
        });
    </script>
}

<div class="row justify-content-center">
    <div class="col-sm-6 bg-white rounded-3 border border-purple">
        <div class="text-end pt-3">
        <button type="button" class="btn btn-sm bg-darkPurple text-white rounded-circle " data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true"
                    title="<p>@Html.Translate("TT_EDITSTEP")</p>">
                ?
        </button>
        </div>
        <form asp-action="Edit" asp-route-tutorialId="@Model.TutorialId" method="post">
            <div class="form-group text-center mt-3">
                <h1>@ViewData["Title"]</h1>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="TutorialId" value="@Model.TutorialId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-center">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div> 
            <div class="form-group text-center">
                <label asp-for="Content" class="control-label"></label>
                <input type="hidden" asp-for="Content" id="contentInput" value="" />
                <div id="editor">
                    <h1>Texto</h1>
                </div>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group text-center py-3">
                <input type="submit" value="@Html.Translate("LB_SAVE")" class="btn bg-purple text-white " />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Step" asp-route-tutorialId="@Model.TutorialId">@Html.Translate("LB_GOBACKTOSTEPLIST")</a>
</div>

MelodyCircle/Views/Step/Index.cshtml
@using MelodyCircle.Data
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MelodyCircle.ExtensionMethods
@model IEnumerable<MelodyCircle.Models.Step>
@inject ApplicationDbContext Context
@inject UserManager<User> UserManager
@{ var cntStep = 0; } 

@{
    ViewData["Title"] = ViewBag.Title;
}

@* Eduardo Andrade, Rodrigo Nogueira, Guilherme Bernardino *@

@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>
    @* <script src="~/js/site.js"></script> *@

    <script>
        let quill = new Quill('#editor');
        let stepDivs = document.getElementsByName("stepDiv");
        let descriptionDiv = document.getElementById("descriptionDiv");
        let stepData = [];
        let tutorialDescription = @Html.Raw(Context.Tutorials.Where(elem => elem.Title == ViewData["Title"].ToString()).First().Description);
        
        
        function convertToHtml(editor, contents) {
            editor.setContents(contents);
            return editor.root.innerHTML;
        }

        @if (Model != null && Model.Any())
        {
            @foreach (var step in Model)
            {
                @:stepData.push(@Html.Raw(step.Content));
            }
        }

        descriptionDiv.innerHTML = convertToHtml(quill, tutorialDescription);

        for (let cnt = 0; cnt < stepData.length; cnt++) {
            stepDivs[cnt].innerHTML = convertToHtml(quill, stepData[cnt]);
        }

        document.addEventListener('DOMContentLoaded', function () {
            @if (User.Identity.IsAuthenticated && User.Identity.Name == ViewBag.Creator)
            {
                @:initSortable();
            }
        });

        function initSortable() {
            var stepList = document.getElementById('stepList');
            new Sortable(stepList, {
                group: 'shared',
                animation: 150,
                draggable: ".step-div",
                handle: '.drag-handle',
                onEnd: updateOrder
            });

            var centralMenu = document.getElementById('centralMenu');
            new Sortable(centralMenu, {
                group: 'shared',
                animation: 150,
                draggable: ".step-div",
                handle: '.drag-handle',
                onEnd: updateOrder
            });
        }

        function updateOrder(evt) {
            var stepOrder = Array.from(evt.to.children).map(function (step) {
                return step.getAttribute('data-step-id');
            });


            fetch('/Step/UpdateOrder', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(stepOrder)
            })
                .then(function (response) { return response.json(); })
                .then(function (data) {

                    if (data && data.success) {
                        var centralMenuElements = document.querySelectorAll('#centralMenu .step-div');

                        var centralMenuElementsMap = {};

                        centralMenuElements.forEach(function (element) {
                            var id = element.getAttribute('data-step-id');
                            centralMenuElementsMap[id] = element;
                        });

                        var centralMenu = document.getElementById('centralMenu');

                        centralMenu.innerHTML = '';

                        stepOrder.forEach(function (id) {
                            var element = centralMenuElementsMap[id];
                            if (element)
                                centralMenu.appendChild(element);
                        });
                    }
                })
                .catch(function (error) { console.error(error); });
        }


    </script>

    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css" rel="stylesheet" />
}

@* LATERAL MENU *@
<div class="row justify-content-around">
    <aside class="col-md-2 h-100 bg-white rounded-3 border-purple">
        <h2 class="p-2 pt-3 text-center">@Html.Translate("LB_STEPS")</h2>

        <div id="stepList" class="pb-3">
            @if (Model != null && Model.Any())
            {
                var userId = UserManager.GetUserId(User);
                Guid tutoId = ViewBag.TutorialId;
                var subscription = Context.SubscribeTutorials.Where(s => s.User.Id.ToString() == userId).FirstOrDefault(st => st.User.Id.ToString() == userId && st.TutorialId == tutoId);

                if (subscription != null)
                {
                    <div class="container">
                        <div class="progress">
                            @{
                                var completionPercentage = subscription != null ? subscription.CompletedSteps.CalculateCompletionPercentage(Model.Count(), 0) : 0;
                            }
                            <div class="progress-bar bg-purple" role="progressbar" aria-valuenow="@completionPercentage" aria-valuemin="0" aria-valuemax="100" style="width: @completionPercentage%">
                                @completionPercentage%
                            </div>
                        </div>
                    </div>
                }

                @foreach (var (step, index) in Model.Select((Value, Index) => (Value, Index)))
                {
                    <div class="col justify-content-evenly mt-3 step-div rounded-2 p-2 border-purple" data-step-id="@step.Id">
                        <div class="drag-handle">
                            <div class="text-center">
                                <span class="text-wrap text-break">@Html.DisplayFor(_ => step.Title)</span>
                            </div>

                            <div class="d-flex justify-content-end mt-2">
                                @if (User.Identity.IsAuthenticated && User.Identity.Name == ViewBag.Creator)
                                {
                                    <a href="@Url.Action("Edit", new { id = step.Id })">
                                        <img src="~/img/edit-black.svg" alt="Edit step" class="icon" />
                                    </a>
                                    <a href="@Url.Action("Delete", new { id = step.Id })">
                                        <img src="~/img/delete.svg" alt="Delete step" class="icon" />
                                    </a>
                                }

                                @if (subscription != null && User.Identity.IsAuthenticated && User.Identity.Name != ViewBag.Creator)
                                {
                                    <form method="post" asp-action="CompleteStep" asp-route-tutorialId="@step.TutorialId" asp-route-stepId="@step.Id">
                                        <button class="border-purple bg-purple rounded" type="submit">
                                            <img src="~/img/check.svg" alt="Complete step" />
                                        </button>
                                    </form>
                                }
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p class="mt-3">@Html.Translate("LB_NOCONTENT")</p>
            }


        </div>
        @* END OF LATERAL MENU *@

        @if (User.Identity.IsAuthenticated)
        {
            @if (User.Identity.Name == ViewBag.Creator)
            {
                <div class="d-flex justify-content-center my-3">
                    <a asp-action="Create" class="btn bg-purple text-white rounded-circle addStepbutton" asp-route-tutorialId="@ViewBag.TutorialId">+</a>
                </div>
            }
        }

    </aside>

    @* CENTRAL MENU *@
    <div class="col-md-8">
        <div class="row d-flex justify-content-center  text-center ">
            <h1 class="align-self-center">@ViewData["Title"]</h1>
            <h3 class="align-self-center">@ViewBag.Creator</h3>
        </div>
        <div>
            <div class="d-flex justify-content-center"><h4>@Html.Translate("LB_DESCRIPTION")</h4></div>
            
            <section id="descriptionDiv" name="descriptionDiv" class="border-purple bg-white rounded-3 py-2 px-1"></section>
        </div>

        <div id="centralMenu">
            @foreach (var step in Model)
            {
                <div class="my-3 step-div" data-step-id="@step.Id">
                    <div class="d-flex justify-content-start drag-handle">
                        <h4>@string.Concat(++step.Order, " - ", step.Title)</h4>
                    </div>

                    <section id="stepDiv" name="stepDiv" class="border-purple bg-white rounded-3 py-2 px-1"></section>
                </div>

            }
        </div>
    </div>
    @* END OF CENTRAL MENU *@

    <input type="hidden" id="editor" name="editor" value="" />


</div>

<div class="text-end">
    <button type="button" class="btn btn-sm bg-darkPurple text-white rounded-circle floating-button-left" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true"
            title="<p>@Html.Translate("TT_STEP")</p>">
        ?
    </button>
</div>



<div class="d-flex justify-content-center align-items-center">
    <button type="button" onclick="history.back();" class="btn bg-purple text-white">
        Voltar Atrás
    </button>
</div>