MelodyCircle/Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace MelodyCircle.Models
{
    public class Comment
    {
        /* Rodrigo Nogueira */
        public Guid Id { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime CreatedAt { get; set; }

        public ForumPost ForumPost { get; set; }

        public Guid ForumPostId { get; set; }

        public User User { get; set; }

        public string UserId { get; set; }
    }
}

MelodyCircle/Controllers/ForumController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MelodyCircle.Data;
using MelodyCircle.Models;
using System.Security.Claims;

namespace MelodyCircle.Controllers
{
    public class ForumController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ForumController(ApplicationDbContext context)
        {
            _context = context;
        }

        //// GET: Forum
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.ForumPost.OrderBy(elem => elem.Id)
        //        .Take(1).ToListAsync());
        //}

        /* Eduardo Andrade */
        public async Task<IActionResult> Posts(Guid lastId)
        {
            var forumPosts = await _context.ForumPost.Where(elem => (elem.Id > lastId))
                .OrderBy(elem => elem.Id)
                .Take(3)
                .ToListAsync();

            return PartialView("_PostsPartial", forumPosts);
        }

        /* Rodrigo Nogueira */
        // GET: Forum/Create
        public IActionResult Create()
        {
            return View();
        }

        /* Rodrigo Nogueira */
        // POST: Forum/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content")] ForumPost forumPost)
        {
            bool hasValidationError = false;

            if (string.IsNullOrEmpty(forumPost.Title))
            {
                ModelState.AddModelError(nameof(forumPost.Title), "O título é obrigatório");
                hasValidationError = true;
            }

            if (string.IsNullOrEmpty(forumPost.Content))
            {
                ModelState.AddModelError(nameof(forumPost.Content), "O conteúdo é obrigatório");
                hasValidationError = true;
            }

            if (hasValidationError)
                return View(forumPost);

            if (ModelState.IsValid)
            {
                forumPost.Id = Guid.NewGuid();
                forumPost.IsClosed = false;

                _context.Add(forumPost);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        /* Rodrigo Nogueira */
        // GET: Forum/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumPost = await _context.ForumPost.FindAsync(id);
            if (forumPost == null)
            {
                return NotFound();
            }
            return View(forumPost);
        }

        /* Rodrigo Nogueira */
        // POST: Forum/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Title,Content")] ForumPost forumPost)
        {
            bool hasValidationError = false;

            if (string.IsNullOrEmpty(forumPost.Title))
            {
                ModelState.AddModelError(nameof(forumPost.Title), "O título é obrigatório");
                hasValidationError = true;
            }

            if (string.IsNullOrEmpty(forumPost.Content))
            {
                ModelState.AddModelError(nameof(forumPost.Content), "O conteúdo é obrigatório");
                hasValidationError = true;
            }

            if (hasValidationError)
                return View(forumPost);

            if (id != forumPost.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Update(forumPost);
                await _context.SaveChangesAsync();
            }

            return View(forumPost);
        }

        /* Rodrigo Nogueira */
        // GET: Forum/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var forumPost = await _context.ForumPost
                .FirstOrDefaultAsync(m => m.Id == id);

            if (forumPost == null)
                return NotFound();

            return View(forumPost);
        }

        /* Rodrigo Nogueira */
        // POST: Forum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var forumPost = await _context.ForumPost.FindAsync(id);

            if (forumPost != null)
                _context.ForumPost.Remove(forumPost);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        /* Rodrigo Nogueira */
        // GET: Forum/Comments/5
        public async Task<IActionResult> Comments(Guid? id)
        {
            if (id == null)
                return NotFound();

            var forumPost = await _context.ForumPost
                .Include(fp => fp.Comments)
                .ThenInclude(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (forumPost == null)
                return NotFound();

            var isClosed = forumPost.IsClosed;

            return View(forumPost);
        }

        /* Rodrigo Nogueira */
        // POST: Forum/Comment/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comment(Guid id, [Bind("Content")] Comment comment)
        {
            var forumPost = await _context.ForumPost.FindAsync(id);

            if (forumPost == null || forumPost.IsClosed)
                return RedirectToAction(nameof(Comments), new { id = id });

            if (string.IsNullOrEmpty(comment.Content))
            {
                ModelState.AddModelError(nameof(comment.Content), "Comment can not be empty");
                TempData["ErrorMessage"] = "Comment can not be empty";
            }

            else
            {
                comment.Id = Guid.NewGuid();
                comment.CreatedAt = DateTime.Now;
                comment.ForumPostId = id;

                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                comment.UserId = userId;

                _context.Add(comment);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Comments), new { id = id });
        }

        /* Rodrigo Nogueira */
        // POST: Forum/ClosePost/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClosePost(Guid id)
        {
            var forumPost = await _context.ForumPost.FindAsync(id);

            if (forumPost == null)
                return NotFound();

            await _context.SaveChangesAsync();

            return View("ClosePost", forumPost);
        }

        /* Rodrigo Nogueira */
        // POST: Forum/ConfirmClosePost/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmClosePost(Guid id)
        {
            var forumPost = await _context.ForumPost.FindAsync(id);

            if (forumPost == null)
                return NotFound();

            forumPost.IsClosed = true;

            await _context.SaveChangesAsync();

            return View("ClosePostConfirmation", forumPost);
        }

        /* Rodrigo Nogueira */
        private bool ForumPostExists(Guid id)
        {
            return _context.ForumPost.Any(e => e.Id == id);
        }
    }
}

MelodyCircle/Views/Forum/ClosePost.cshtml
@using MelodyCircle.ExtensionMethods
@model ForumPost

@{
    ViewData["Title"] = @Html.Translate("LB_CLOSEPOST");
}

@* André Nunes, Rodrigo Nogueira *@

<div class="border border-purple bg-white text-center p-2 p-sm-2 p-md-3 p-lg-5 rounded-3 mx-auto w-50">
    <div class="d-flex flex-column align-items-center">
        <h1>@Html.Translate("LB_CONFIRMCLOSEPOST")</h1>

        <p>@Html.Translate("LB_WISHCLOSEPOST")?</p>
        <p><strong>@Html.Translate("LB_TITLE"): </strong>@Model.Title</p>
        <p><strong>@Html.Translate("LB_CONTENT"): </strong>@Model.Content</p>

        <form asp-action="ConfirmClosePost" asp-route-id="@Model.Id" method="post" class="text-center">
            <button type="submit" class="btn btn-danger">@Html.Translate("LB_CONFIRM")</button>
            <a asp-action="Comments" asp-controller="Forum" asp-route-id="@Model.Id" class="btn btn-secondary">@Html.Translate("LB_CANCEL")</a>
        </form>
    </div>
</div>

MelodyCircle/Views/Forum/ClosePostConfirmation.cshtml
@using MelodyCircle.ExtensionMethods
@{
    ViewData["Title"] = @Html.Translate("LB_CLOSEDPOST");
}

@* André Nunes, Rodrigo Nogueira *@

<div class="border border-purple bg-white text-center p-2 p-sm-2 p-md-3 p-lg-5 rounded-3 mx-auto w-50">
    <h1>@Html.Translate("LB_CLOSEDPOSTSUCCES")</h1>

    <a asp-action="Index" asp-controller="Home" class="btn bg-purple text-white mt-4">@Html.Translate("LB_GOBACK_HP")</a>
</div>

MelodyCircle/Views/Forum/Comments.cshtml
@using MelodyCircle.ExtensionMethods
@using System.Text.Json
@using Newtonsoft.Json
@model MelodyCircle.Models.ForumPost


@* Eduardo Andrade, Rodrigo Nogueira, Guilherme Bernardino *@
@section head {
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css" rel="stylesheet" />
}

@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            let contentDiv = document.getElementById("contentDiv");
            if (contentDiv) {
                let quillView = new Quill(contentDiv, {
                    theme: 'bubble',
                    readOnly: true
                });

                let content = @Html.Raw(Json.Serialize(Model.Content));
                quillView.setContents(JSON.parse(content));
            }

            let quillComment = new Quill('#editor-comment', {
                placeholder: 'Write a comment...',
                theme: 'snow'
            });

            document.querySelector('#comment-form').addEventListener('submit', function (event) {
                let content = quillComment.root.innerHTML;
                let isEmpty = content.trim() === '<p><br></p>';
                if (isEmpty) {
                    event.preventDefault();
                    document.getElementById('comment-error').textContent = "Comment cannot be empty";
                } else {
                    document.getElementById('hiddenContent').value = content;
                }
            });

            let comments = @Html.Raw(JsonConvert.SerializeObject(Model.Comments.Select(c => c.Content)));
            comments.forEach((comment, index) => {
                let commentDiv = document.createElement('div');
                commentDiv.classList.add('comment-content-view');
                document.body.appendChild(commentDiv);
                let quillCommentView = new Quill(commentDiv, {
                    theme: 'bubble',
                    readOnly: true
                });
                quillCommentView.setContents(JSON.parse(comment));
            });
        });
    </script>
}

<div class="border border-purple bg-white text-dark p-3 rounded-3 text-center mx-auto" style="width: 50%;">
    <h1>@Model.Title</h1>
    <div id="contentDiv"></div>
</div>

<div class="border border-purple bg-white text-dark p-3 rounded-3 text-center mx-auto my-4 w-50">
    @if (!Model.IsClosed)
    {
        @if (User.Identity.IsAuthenticated)
        {
            <h3>@Html.Translate("LB_ADDCOMMENTS")</h3>
            <form asp-action="Comment" asp-route-id="@Model.Id" method="post" id="comment-form">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div id="editor-comment" style="height: 150px;"></div>
                    <input type="hidden" name="Content" id="hiddenContent" />
                </div>
                <div id="comment-error" class="text-danger"></div>
                <button type="submit" class="btn bg-purple text-white mt-3">@Html.Translate("LB_ADDCOMMENTS")</button>
            </form>
        }
        else
        {
            <p>Please log in to comment</p>
        }
    }
    else
    {
        <div class="text-center my-4"><p>@Html.Translate("LB_COMMENTINFO")</p></div>
    }

    <hr>

    @if (Model.Comments.Any())
    {
        <h2>@Html.Translate("LB_COMMENTS")</h2>
        foreach (var comment in Model.Comments)
        {
            <div class="bg-light p-3 mb-3 rounded">
                <div class="d-flex justify-content-between mb-2">
                    <div><a asp-action="Profile" asp-controller="User" asp-route-id="@comment.User.UserName" class="text-decoration-none text-primary">@comment.User.UserName</a></div>
                    <div class="text-muted">@comment.CreatedAt.ToString("dd-MM-yyyy HH:mm")</div>
                </div>
                <div name="commentContent" class="text-start">@Html.Raw(comment.Content)</div>
            </div>
        }
    }
    else
    {
        <div class="text-center my-4"><p>@Html.Translate("LB_NOCOMMENTS")</p></div>
    }
</div>

MelodyCircle/Views/Forum/Create.cshtml
@using MelodyCircle.ExtensionMethods
@model MelodyCircle.Models.ForumPost

@* André Nunes, Rodrigo Nogueira *@

@{
    ViewData["Title"] = @Html.Translate("LB_CREATEPOST");
}
@section head {
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css" rel="stylesheet" />
}
@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.js"></script>
    <script>
        const quill = new Quill('#editor', {
            placeholder: 'Compose an epic...',
            theme: 'snow',
        });
        let contentInput = document.getElementById("contentInput");
        contentInput.value = JSON.stringify(quill.getContents());
        quill.on('text-change', function (delta, oldDelta, source) {
            contentInput.value = JSON.stringify(quill.getContents());
        })
    </script>
}


<h1 class="text-center">Forum Post</h1>

<div class="row  justify-content-center">
    <div class="border border-purple bg-white text-dark p-2 p-sm-2 p-md-3 p-lg-5 rounded-3 text-center w-50 align-items-center">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input type="hidden" asp-for="Content" id="contentInput" value="" />
                @* <textarea style="visibility: hidden;" asp-for="Content" class="" rows="4"></textarea> *@
                <div id="editor">
                    <p>Hello, <strong>World</strong></p>
                </div>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Html.Translate("LB_CREATE")" class="btn bg-purple text-white mt-4" />
            </div>
        </form>
    </div>
</div>

<div class="text-center mt-2">
    <a asp-action="Index" asp-controller="Home">@Html.Translate("LB_GOBACK_HP")</a>
</div>

MelodyCircle/Views/Forum/_PostsPartial.cshtml
@using System.Security.Claims
@using MelodyCircle.ExtensionMethods
@using Microsoft.AspNetCore.Identity
@using MelodyCircle.Data
@model IEnumerable<ForumPost>
@inject UserManager<User> UserManager
@inject ApplicationDbContext Context

@* Eduardo Andrade, André Nunes, Rodrigo Nogueira *@

@foreach (var item in Model)
{
    <div class="border border-purple bg-white text-dark p-2 p-sm-2 p-md-3 p-lg-5 rounded-3 text-center m-2" style="width: 24%;" data-tutorial-id="@item.Id">
        <h1 class="bold text-truncate d-block">@Html.DisplayFor(modelItem => item.Title)</h1>
        <hr>
        <section id="stepDiv" name="stepDiv" class="py-2 px-1"></section>
        <a href="@Url.Action("Comments", "Forum", new { id = item.Id })" class="btn bg-purple text-white mt-4">@Html.Translate("LB_SEECOMMENTS")</a>
        @if (!item.IsClosed && (User.IsInRole("Admin") || User.IsInRole("Mod")))
        {
            <form asp-action="ClosePost" asp-controller="Forum" asp-route-id="@item.Id" method="post">
                <button type="submit" class="btn btn-danger mt-2 mb-1">@Html.Translate("LB_CLOSEPOST")</button>
            </form>
            @Html.AntiForgeryToken()
        }
    </div>
}